# Generated by Django 3.0.8 on 2020-07-20 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20200719_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='Subscription_state',
            field=models.CharField(default='not active', max_length=255),
        ),
    ]
