# Generated by Django 3.0.8 on 2020-07-20 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_subscription_subscription_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='Subscription_state',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='state',
            field=models.CharField(default='not active', max_length=255),
        ),
    ]
